// Ys III credits script -- generated by scripts/tasks/generate_credits.py.
// Do not edit by hand; edit scripts/data/credits.yaml and re-run `to-asm`.

cred_null: equ 0x002511a8

credits_script:
.dw 0x00000000, 0x00000000, 0x00000001, 0x0000000c, 0x00000000, cred_null
.dw 0x00000030, 0x00000060, 0x00000002, 0x00000008, 0x00000018, cred_english_fan_translation
.dw 0x00000030, 0x00000090, 0x00000002, 0x00000008, 0x00000018, cred_lead
.dw 0x00000090, 0x000000a8, 0x00000002, 0x00000008, 0x00000018, cred_kaisaan
.dw 0x00000000, 0x00000000, 0x00000003, 0x00000096, 0x00000000, cred_null
.dw 0x00000001, 0x00000002, 0x00000006, 0x00000028, 0x00000018, cred_null
.dw 0x00000030, 0x00000090, 0x00000002, 0x00000008, 0x00000018, cred_translation
.dw 0x00000090, 0x000000a8, 0x00000002, 0x00000008, 0x00000018, cred_josepmc
.dw 0x00000000, 0x00000000, 0x00000003, 0x00000096, 0x00000000, cred_null
.dw 0x00000001, 0x00000002, 0x00000006, 0x00000028, 0x00000018, cred_null
.dw 0x00000030, 0x00000090, 0x00000002, 0x00000008, 0x00000018, cred_graphics_video
.dw 0x00000090, 0x000000a8, 0x00000002, 0x00000008, 0x00000018, cred_etokapa
.dw 0x00000000, 0x00000000, 0x00000003, 0x00000096, 0x00000000, cred_null
.dw 0x00000001, 0x00000002, 0x00000006, 0x00000028, 0x00000018, cred_null
.dw 0x00000030, 0x00000090, 0x00000002, 0x00000008, 0x00000018, cred_programming
.dw 0x00000090, 0x000000a8, 0x00000002, 0x00000008, 0x00000018, cred_kaisaan
.dw 0x00000090, 0x000000c0, 0x00000002, 0x00000008, 0x00000018, cred_everdred
.dw 0x00000000, 0x00000000, 0x00000003, 0x00000096, 0x00000000, cred_null
.dw 0x00000001, 0x00000003, 0x00000006, 0x00000028, 0x00000018, cred_null
.dw 0x00000030, 0x00000090, 0x00000002, 0x00000008, 0x00000018, cred_testing_feedback
.dw 0x00000090, 0x000000a8, 0x00000002, 0x00000008, 0x00000018, cred_etokapa
.dw 0x00000090, 0x000000c0, 0x00000002, 0x00000008, 0x00000018, cred_jazzysan
.dw 0x00000090, 0x000000d8, 0x00000002, 0x00000008, 0x00000018, cred_wagamamalullaby
.dw 0x00000090, 0x000000f0, 0x00000002, 0x00000008, 0x00000018, cred_dragonbleapiece
.dw 0x00000000, 0x00000000, 0x00000003, 0x00000096, 0x00000000, cred_null
.dw 0x00000001, 0x00000005, 0x00000006, 0x00000028, 0x00000018, cred_null
.dw 0x00000030, 0x00000090, 0x00000002, 0x00000008, 0x00000018, cred_special_thanks
.dw 0x00000090, 0x000000a8, 0x00000002, 0x00000008, 0x00000018, cred_all_lost_kefin_contributors
.dw 0x00000090, 0x000000c0, 0x00000002, 0x00000008, 0x00000018, cred_all_supporters
.dw 0x00000090, 0x000000d8, 0x00000002, 0x00000008, 0x00000018, cred_you
.dw 0x00000090, 0x000000f0, 0x00000002, 0x00000008, 0x00000018, cred_line
.dw 0x00000000, 0x00000000, 0x00000003, 0x00000096, 0x00000000, cred_null
.dw 0x00000000, 0x00000005, 0x00000006, 0x00000028, 0x00000018, cred_null
.dw 0x00000000, 0x00000000, 0xffffffff, 0x00000000, 0x00000000, cred_null

// brand-new lines referenced by YAML `str` entries
cred_english_fan_translation: .str "English Fan Translation"
cred_lead: .str "Lead"
cred_kaisaan: .str "Kaisaan"
cred_translation: .str "Translation"
cred_josepmc: .str "JosepMC"
cred_graphics_video: .str "Graphics & Video"
cred_etokapa: .str "Etokapa"
cred_programming: .str "Programming"
cred_everdred: .str "Everdred"
cred_testing_feedback: .str "Testing & Feedback"
cred_jazzysan: .str "Jazzysan"
cred_wagamamalullaby: .str "wagamamalullaby"
cred_dragonbleapiece: .str "DRAGONBLEAPIECE"
cred_special_thanks: .str "Special Thanks"
cred_all_lost_kefin_contributors: .str "All Lost Kefin Contributors"
cred_all_supporters: .str "All Supporters"
cred_you: .str "You!"
cred_line: .str ""
.align 4
